openapi: 3.0.0
info:
  title: Tasks api
  description: Tasks CRUD operations
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Local development server
paths:
  /tasks:
    get:
      summary: Get all tasks
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                tasks:
                  $ref: "#/components/schemas/Task"
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created successfully
  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Task found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found
    patch:
      summary: Update a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "200":
          description: Task updated successfully
        "404":
          description: Task not found
    delete:
      summary: Delete a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Task deleted successfully
        "404":
          description: Task not found
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          example: "1"
        name:
          type: string
          required: true
          example: "Sample Task"
        completed:
          type: boolean
          example: true
